### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by DenTelezhkin** [lucasmedeirosleite/EasyMapping#62]
- [x] Change signature of CoreData mapping block (#57)
- [x] Provide relevant examples with new syntax on Objective-C
- [x] Examples on Swift
